### ISSUE TITLE
averageResult is not shown in sample output

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-rest-client-async#23]
averageResult is mentioned in the guide but not shown in the sample output.  This may be confusing to some users.

This is a nice-to-have suggestion can be handled later.

**Comment by gkwan-ibm** [comment]
@yeekangc  OptionalDouble is used for averageResult, that why averageResult is not shown by the `/api/jobs` if no job is created. IMO, it is good behavior. I suggest to add a paragraph to explain it instead of showing `{"count":0,"results":[], "averageResult":0}` or  `{"count":0,"results":[], "averageResult":null}` (if a list is empty, average is invalid).

**Comment by yeekangc** [comment]
Yes, it will be useful to explain the API appropriately.
